import 'package:analyzer/dart/element/element.dart';
import 'package:best_theme_annotation/best_theme_annotation.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

class BestGenerator extends GeneratorForAnnotation<BestTheme> {
  @override
  String generateForAnnotatedElement(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) {
    // Robust structural matching that works across all old/new analyzer versions
    final elementTypeName = element.runtimeType.toString();
    if (!elementTypeName.contains('ClassElement')) {
      throw InvalidGenerationSourceError(
        'BestTheme annotation can only be applied to a class.',
        element: element,
      );
    }

    final buffer = StringBuffer();
    final className = element.displayName;

    // Separate fields into distinct UI Token buckets based on type matching
    final colorVars = <String>[];
    final textStyleVars = <String>[];
    final assetVars = <String>[];

    // Safely cast to ClassElement structure using generic fallbacks
    final classElement = element as ClassElement;

    for (final field in classElement.fields) {
      if (field.isStatic && field.isConst) {
        final typeStr = field.type.getDisplayString();
        if (typeStr.contains('BestColor')) {
          colorVars.add(field.displayName);
        } else if (typeStr.contains('BestTextStyle')) {
          textStyleVars.add(field.displayName);
        } else if (typeStr.contains('BestAsset')) {
          assetVars.add(field.displayName);
        }
      }
    }

    buffer.writeln('// ignore_for_file: non_constant_identifier_names');
    buffer.writeln(
        '// **************************************************************************');
    buffer.writeln('// * *');
    buffer.writeln('// * 🎨 BEST THEME GENERATOR 🎨                     *');
    buffer.writeln('// * *');
    buffer.writeln(
        '// * Custom code generated by: Dosty Pshtiwan                               *');
    buffer.writeln('// * *');
    buffer.writeln(
        '// * ⚡ Automatic theme management for Flutter apps ⚡        *');
    buffer.writeln('// * *');
    buffer.writeln(
        '// * Generated on: ${DateTime.now().toString().split(' ')[0]}                                *');
    buffer.writeln('// * *');
    buffer.writeln(
        '// **************************************************************************');
    buffer.writeln('');
    buffer.writeln(
        '// This is a custom generator for handling theme colors, typography, and assets');
    buffer.writeln('// Generated for: $className');
    buffer.writeln('');

    // ── 1. ThemeExtension class ──────────────────────────────────────────
    buffer.writeln('@immutable');
    buffer.writeln(
        'class _\$${className}Theme extends ThemeExtension<_\$${className}Theme> {');

    // Declare specific type properties matching tokens fields
    for (final v in colorVars) buffer.writeln('  final Color $v;');
    for (final v in textStyleVars) buffer.writeln('  final TextStyle $v;');
    for (final v in assetVars) buffer.writeln('  final String $v;');
    buffer.writeln('');

    // Typed constructor injection
    buffer.writeln('  const _\$${className}Theme({');
    for (final v in colorVars) buffer.writeln('    required this.$v,');
    for (final v in textStyleVars) buffer.writeln('    required this.$v,');
    for (final v in assetVars) buffer.writeln('    required this.$v,');
    buffer.writeln('  });');
    buffer.writeln('');

    // Light theme factory mapping directly to compile-time configuration fields
    buffer.writeln('  factory _\$${className}Theme.light() {');
    buffer.writeln('    return _\$${className}Theme(');
    for (final v in colorVars) buffer.writeln('      $v: $className.$v.light,');
    for (final v in textStyleVars)
      buffer.writeln('      $v: $className.$v.light,');
    for (final v in assetVars) buffer.writeln('      $v: $className.$v.light,');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('');

    // Dark theme factory mapping directly to compile-time configuration fields
    buffer.writeln('  factory _\$${className}Theme.dark() {');
    buffer.writeln('    return _\$${className}Theme(');
    for (final v in colorVars) buffer.writeln('      $v: $className.$v.dark,');
    for (final v in textStyleVars)
      buffer.writeln('      $v: $className.$v.dark,');
    for (final v in assetVars) buffer.writeln('      $v: $className.$v.dark,');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('');

    // Type safe CopyWith signature
    buffer.writeln('  @override');
    buffer.writeln('  _\$${className}Theme copyWith({');
    for (final v in colorVars) buffer.writeln('    Color? $v,');
    for (final v in textStyleVars) buffer.writeln('    TextStyle? $v,');
    for (final v in assetVars) buffer.writeln('    String? $v,');
    buffer.writeln('  }) {');
    buffer.writeln('    return _\$${className}Theme(');
    for (final v in colorVars) buffer.writeln('      $v: $v ?? this.$v,');
    for (final v in textStyleVars) buffer.writeln('      $v: $v ?? this.$v,');
    for (final v in assetVars) buffer.writeln('      $v: $v ?? this.$v,');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('');

    // Fluid interpolation support across all type layouts
    buffer.writeln('  @override');
    buffer.writeln(
        '  _\$${className}Theme lerp(ThemeExtension<_\$${className}Theme>? other, double t) {');
    buffer.writeln('    if (other is! _\$${className}Theme) return this;');
    buffer.writeln('    return _\$${className}Theme(');
    for (final v in colorVars)
      buffer.writeln('      $v: Color.lerp($v, other.$v, t)!,');
    for (final v in textStyleVars)
      buffer.writeln('      $v: TextStyle.lerp($v, other.$v, t)!,');
    for (final v in assetVars)
      buffer.writeln(
          '      $v: t < 0.5 ? $v : other.$v,'); // Discrete string toggle jump
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('');

    buffer.writeln('  static _\$${className}Theme of(BuildContext context) =>');
    buffer
        .writeln('      Theme.of(context).extension<_\$${className}Theme>()!;');
    buffer.writeln('}');
    buffer.writeln('');

    // ── 2. Abstract base theme class (Appends extension safely after user configuration) ─────────────────
    buffer.writeln('abstract class _\$$className {');
    buffer.writeln('  _\$$className();');
    buffer.writeln('');
    buffer.writeln('  /// Override to customize the light theme.');
    buffer.writeln('  ThemeData buildLightTheme(ThemeData theme) => theme;');
    buffer.writeln('');
    buffer.writeln('  /// Override to customize the dark theme.');
    buffer.writeln('  ThemeData buildDarkTheme(ThemeData theme) => theme;');
    buffer.writeln('');
    buffer.writeln('  ThemeData get lightTheme {');
    buffer.writeln(
        '    final baseTheme = ThemeData(brightness: Brightness.light);');
    buffer.writeln('    final userTheme = buildLightTheme(baseTheme);');
    buffer.writeln('    return userTheme.copyWith(');
    buffer.writeln(
        '      extensions: [...userTheme.extensions.values, _\$${className}Theme.light()],');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('');
    buffer.writeln('  ThemeData get darkTheme {');
    buffer.writeln(
        '    final baseTheme = ThemeData(brightness: Brightness.dark);');
    buffer.writeln('    final userTheme = buildDarkTheme(baseTheme);');
    buffer.writeln('    return userTheme.copyWith(');
    buffer.writeln(
        '      extensions: [...userTheme.extensions.values, _\$${className}Theme.dark()],');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.writeln('');

    // ── 3. Public Standalone StatefulWidget (With Storage Adapter Injection) ──────────────────────────────
    buffer.writeln('class ${className}Material extends StatefulWidget {');
    buffer.writeln('  final ThemeMode initialMode;');
    buffer.writeln('  final BestThemeStorage? storage;');
    buffer.writeln(
        '  final Widget Function(BuildContext context, ThemeMode mode, ThemeData lightTheme, ThemeData darkTheme) builder;');
    buffer.writeln('');
    buffer.writeln('  const ${className}Material({');
    buffer.writeln('    super.key,');
    buffer.writeln('    required this.builder,');
    buffer.writeln('    this.initialMode = ThemeMode.system,');
    buffer.writeln('    this.storage,');
    buffer.writeln('  });');
    buffer.writeln('');
    buffer.writeln(
        '  static _${className}MaterialState of(BuildContext context) =>');
    buffer.writeln(
        '      context.findAncestorStateOfType<_${className}MaterialState>()!;');
    buffer.writeln('');
    buffer.writeln('  @override');
    buffer.writeln(
        '  State<${className}Material> createState() => _${className}MaterialState();');
    buffer.writeln('}');
    buffer.writeln('');

    // ── 4. State (Handles reading and writing asynchronously) ─────────────────────────────────────────
    buffer.writeln(
        'class _${className}MaterialState extends State<${className}Material> {');
    buffer.writeln('  late ThemeMode _mode;');
    buffer.writeln('  late final $className _instance;');
    buffer.writeln('');
    buffer.writeln('  @override');
    buffer.writeln('  void initState() {');
    buffer.writeln('    super.initState();');
    buffer.writeln('    _instance = $className();');
    buffer.writeln('    _mode = widget.initialMode;');
    buffer.writeln('    _loadPersistedTheme();');
    buffer.writeln('  }');
    buffer.writeln('');
    buffer.writeln('  Future<void> _loadPersistedTheme() async {');
    buffer.writeln('    if (widget.storage == null) return;');
    buffer.writeln(
        '    final savedMode = await widget.storage!.loadThemeMode();');
    buffer.writeln('    if (savedMode != null && mounted) {');
    buffer.writeln('      setState(() => _mode = savedMode);');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln('');
    buffer.writeln('  Future<void> _updateMode(ThemeMode mode) async {');
    buffer.writeln('    setState(() => _mode = mode);');
    buffer.writeln('    await widget.storage?.saveThemeMode(mode);');
    buffer.writeln('  }');
    buffer.writeln('');
    buffer.writeln('  void toggle() {');
    buffer.writeln(
        '    final target = _mode == ThemeMode.dark ? ThemeMode.light : ThemeMode.dark;');
    buffer.writeln('    _updateMode(target);');
    buffer.writeln('  }');
    buffer.writeln('');
    buffer.writeln('  void setMode(ThemeMode mode) => _updateMode(mode);');
    buffer.writeln('  void toDark() => _updateMode(ThemeMode.dark);');
    buffer.writeln('  void toLight() => _updateMode(ThemeMode.light);');
    buffer.writeln('');
    buffer.writeln('  @override');
    buffer.writeln('  Widget build(BuildContext context) => widget.builder(');
    buffer.writeln('    context,');
    buffer.writeln('    _mode,');
    buffer.writeln('    _instance.lightTheme,');
    buffer.writeln('    _instance.darkTheme,');
    buffer.writeln('  );');
    buffer.writeln('}');
    buffer.writeln('');

    // ── 5. BuildContext extension ─────────────────────────────────────────
    final extensionName = annotation.read('extensionName').stringValue;
    buffer.writeln('extension ${className}ContextExtension on BuildContext {');
    buffer.writeln(
        '  _\$${className}Theme get $extensionName => _\$${className}Theme.of(this);');
    buffer.writeln(
        '  bool get isDark => Theme.of(this).brightness == Brightness.dark;');
    buffer.writeln(
        '  Color get scaffoldBackgroundColor => Theme.of(this).scaffoldBackgroundColor;');
    buffer.writeln('  Color get primary => Theme.of(this).primaryColor;');
    buffer.writeln(
        '  Color get primaryScheme => Theme.of(this).colorScheme.primary;');
    buffer.writeln(
        '  void toggleTheme() => ${className}Material.of(this).toggle();');
    buffer.writeln(
        '  void setThemeMode(ThemeMode mode) => ${className}Material.of(this).setMode(mode);');
    buffer
        .writeln('  void toDark() => ${className}Material.of(this).toDark();');
    buffer.writeln(
        '  void toLight() => ${className}Material.of(this).toLight();');
    buffer.writeln('}');

    return buffer.toString();
  }
}
