// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'my_theme.dart';

// **************************************************************************
// BestGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names
// **************************************************************************
// *                                                                        *
// *                        🎨 BEST THEME GENERATOR 🎨                     *
// *                                                                        *
// *                    Custom code generated by: Dosty Pshtiwan           *
// *                                                                        *
// *              ⚡ Automatic theme management for Flutter apps ⚡        *
// *                                                                        *
// *                        Generated on: 2026-03-06                       *
// *                                                                        *
// **************************************************************************

// This is a custom generator for handling theme colors
// Generated for: Mytheme

@immutable
class _MythemeTheme extends ThemeExtension<_MythemeTheme> {
  final Color color1;
  final Color color2;
  final Color color3;
  final Color color4;
  final Color grey23;
  final Color grey3;

  const _MythemeTheme({
    required this.color1,
    required this.color2,
    required this.color3,
    required this.color4,
    required this.grey23,
    required this.grey3,
  });

  factory _MythemeTheme.light(List<BestColor> colors) {
    final m = {for (final c in colors) c.name: c};
    return _MythemeTheme(
      color1: m['color1']!.light,
      color2: m['color2']!.light,
      color3: m['color3']!.light,
      color4: m['color4']!.light,
      grey23: m['grey23']!.light,
      grey3: m['grey3']!.light,
    );
  }

  factory _MythemeTheme.dark(List<BestColor> colors) {
    final m = {for (final c in colors) c.name: c};
    return _MythemeTheme(
      color1: m['color1']!.dark,
      color2: m['color2']!.dark,
      color3: m['color3']!.dark,
      color4: m['color4']!.dark,
      grey23: m['grey23']!.dark,
      grey3: m['grey3']!.dark,
    );
  }

  @override
  _MythemeTheme copyWith({
    Color? color1,
    Color? color2,
    Color? color3,
    Color? color4,
    Color? grey23,
    Color? grey3,
  }) {
    return _MythemeTheme(
      color1: color1 ?? this.color1,
      color2: color2 ?? this.color2,
      color3: color3 ?? this.color3,
      color4: color4 ?? this.color4,
      grey23: grey23 ?? this.grey23,
      grey3: grey3 ?? this.grey3,
    );
  }

  @override
  _MythemeTheme lerp(ThemeExtension<_MythemeTheme>? other, double t) {
    if (other is! _MythemeTheme) return this;
    return _MythemeTheme(
      color1: Color.lerp(color1, other.color1, t)!,
      color2: Color.lerp(color2, other.color2, t)!,
      color3: Color.lerp(color3, other.color3, t)!,
      color4: Color.lerp(color4, other.color4, t)!,
      grey23: Color.lerp(grey23, other.grey23, t)!,
      grey3: Color.lerp(grey3, other.grey3, t)!,
    );
  }

  static _MythemeTheme of(BuildContext context) =>
      Theme.of(context).extension<_MythemeTheme>()!;
}

abstract class _$Mytheme {
  final List<BestColor> myColors;

  _$Mytheme({required this.myColors});

  /// Override to customize the light theme.
  /// [theme] already contains the color extension.
  /// Example:
  ///   @override
  ///   ThemeData buildLightTheme(ThemeData theme) => theme.copyWith(
  ///     fontFamily: 'Roboto',
  ///     primaryColor: Colors.blue,
  ///   );
  ThemeData buildLightTheme(ThemeData theme) => theme.copyWith();

  /// Override to customize the dark theme.
  /// [theme] already contains the color extension.
  ThemeData buildDarkTheme(ThemeData theme) => theme.copyWith();

  ThemeData get lightTheme => buildLightTheme(ThemeData(
        brightness: Brightness.light,
        extensions: [_MythemeTheme.light(myColors)],
      ));

  ThemeData get darkTheme => buildDarkTheme(ThemeData(
        brightness: Brightness.dark,
        extensions: [_MythemeTheme.dark(myColors)],
      ));
}

// Use directly: MythemeBestThemeMaterial(builder: (ctx, mode, light, dark) => MaterialApp(...))
class MythemeBestThemeMaterial extends StatefulWidget {
  final ThemeMode initialMode;
  final Widget Function(BuildContext context, ThemeMode mode,
      ThemeData lightTheme, ThemeData darkTheme) builder;

  const MythemeBestThemeMaterial({
    super.key,
    required this.builder,
    this.initialMode = ThemeMode.system,
  });

  static _MythemeBestThemeMaterialState of(BuildContext context) =>
      context.findAncestorStateOfType<_MythemeBestThemeMaterialState>()!;

  @override
  State<MythemeBestThemeMaterial> createState() =>
      _MythemeBestThemeMaterialState();
}

class _MythemeBestThemeMaterialState extends State<MythemeBestThemeMaterial> {
  late ThemeMode _mode;
  late final Mytheme _instance;

  @override
  void initState() {
    super.initState();
    _instance = Mytheme();
    _mode = widget.initialMode;
  }

  void toggle() => setState(() {
        _mode = _mode == ThemeMode.dark ? ThemeMode.light : ThemeMode.dark;
      });

  void setMode(ThemeMode mode) => setState(() => _mode = mode);
// to dark
  void toDark() => setState(() => _mode = ThemeMode.dark);
  // to light
  void toLight() => setState(() => _mode = ThemeMode.light);

  @override
  Widget build(BuildContext context) => widget.builder(
        context,
        _mode,
        _instance.lightTheme,
        _instance.darkTheme,
      );
}

extension MythemeContextExtension on BuildContext {
  _MythemeTheme get myColors => _MythemeTheme.of(this);
  bool get isDark => Theme.of(this).brightness == Brightness.dark;
  Color get scaffoldBackgroundColor => Theme.of(this).scaffoldBackgroundColor;
  Color get primary => Theme.of(this).primaryColor;
  Color get primaryScheme => Theme.of(this).colorScheme.primary;
  void toggleTheme() => MythemeBestThemeMaterial.of(this).toggle();
  void setThemeMode(ThemeMode mode) =>
      MythemeBestThemeMaterial.of(this).setMode(mode);
  void toDark() => MythemeBestThemeMaterial.of(this).toDark();
  void toLight() => MythemeBestThemeMaterial.of(this).toLight();
}
