// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'my_theme.dart';

// **************************************************************************
// BestGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names
// **************************************************************************
// * *
// * 🎨 BEST THEME GENERATOR 🎨                     *
// * *
// * Custom code generated by: Dosty Pshtiwan           *
// * *
// * ⚡ Automatic theme management for Flutter apps ⚡        *
// * *
// * Generated on: 2026-06-19                       *
// * *
// **************************************************************************

// This is a custom generator for handling theme colors, typography, and assets
// Generated for: MyTheme

@immutable
class _MyThemeTheme extends ThemeExtension<_MyThemeTheme> {
  final Color color1;
  final Color color2;
  final Color color3;
  final Color grey23;
  final TextStyle titleLarge;
  final String appLogo;

  const _MyThemeTheme({
    required this.color1,
    required this.color2,
    required this.color3,
    required this.grey23,
    required this.titleLarge,
    required this.appLogo,
  });

  factory _MyThemeTheme.light() {
    return _MyThemeTheme(
      color1: MyTheme.color1.light,
      color2: MyTheme.color2.light,
      color3: MyTheme.color3.light,
      grey23: MyTheme.grey23.light,
      titleLarge: MyTheme.titleLarge.light,
      appLogo: MyTheme.appLogo.light,
    );
  }

  factory _MyThemeTheme.dark() {
    return _MyThemeTheme(
      color1: MyTheme.color1.dark,
      color2: MyTheme.color2.dark,
      color3: MyTheme.color3.dark,
      grey23: MyTheme.grey23.dark,
      titleLarge: MyTheme.titleLarge.dark,
      appLogo: MyTheme.appLogo.dark,
    );
  }

  @override
  _MyThemeTheme copyWith({
    Color? color1,
    Color? color2,
    Color? color3,
    Color? grey23,
    TextStyle? titleLarge,
    String? appLogo,
  }) {
    return _MyThemeTheme(
      color1: color1 ?? this.color1,
      color2: color2 ?? this.color2,
      color3: color3 ?? this.color3,
      grey23: grey23 ?? this.grey23,
      titleLarge: titleLarge ?? this.titleLarge,
      appLogo: appLogo ?? this.appLogo,
    );
  }

  @override
  _MyThemeTheme lerp(ThemeExtension<_MyThemeTheme>? other, double t) {
    if (other is! _MyThemeTheme) return this;
    return _MyThemeTheme(
      color1: Color.lerp(color1, other.color1, t)!,
      color2: Color.lerp(color2, other.color2, t)!,
      color3: Color.lerp(color3, other.color3, t)!,
      grey23: Color.lerp(grey23, other.grey23, t)!,
      titleLarge: TextStyle.lerp(titleLarge, other.titleLarge, t)!,
      appLogo: t < 0.5 ? appLogo : other.appLogo,
    );
  }

  static _MyThemeTheme of(BuildContext context) =>
      Theme.of(context).extension<_MyThemeTheme>()!;
}

abstract class _$MyTheme {
  _$MyTheme();

  /// Override to customize the light theme.
  ThemeData buildLightTheme(ThemeData theme) => theme;

  /// Override to customize the dark theme.
  ThemeData buildDarkTheme(ThemeData theme) => theme;

  ThemeData get lightTheme {
    final baseTheme = ThemeData(brightness: Brightness.light);
    final userTheme = buildLightTheme(baseTheme);
    return userTheme.copyWith(
      extensions: [...userTheme.extensions.values, _MyThemeTheme.light()],
    );
  }

  ThemeData get darkTheme {
    final baseTheme = ThemeData(brightness: Brightness.dark);
    final userTheme = buildDarkTheme(baseTheme);
    return userTheme.copyWith(
      extensions: [...userTheme.extensions.values, _MyThemeTheme.dark()],
    );
  }
}

class MyThemeMaterial extends StatefulWidget {
  final ThemeMode initialMode;
  final BestThemeStorage? storage;
  final Widget Function(BuildContext context, ThemeMode mode,
      ThemeData lightTheme, ThemeData darkTheme) builder;

  const MyThemeMaterial({
    super.key,
    required this.builder,
    this.initialMode = ThemeMode.system,
    this.storage,
  });

  static _MyThemeMaterialState of(BuildContext context) =>
      context.findAncestorStateOfType<_MyThemeMaterialState>()!;

  @override
  State<MyThemeMaterial> createState() => _MyThemeMaterialState();
}

class _MyThemeMaterialState extends State<MyThemeMaterial> {
  late ThemeMode _mode;
  late final MyTheme _instance;

  @override
  void initState() {
    super.initState();
    _instance = MyTheme();
    _mode = widget.initialMode;
    _loadPersistedTheme();
  }

  Future<void> _loadPersistedTheme() async {
    if (widget.storage == null) return;
    final savedMode = await widget.storage!.loadThemeMode();
    if (savedMode != null && mounted) {
      setState(() => _mode = savedMode);
    }
  }

  Future<void> _updateMode(ThemeMode mode) async {
    setState(() => _mode = mode);
    await widget.storage?.saveThemeMode(mode);
  }

  void toggle() {
    final target = _mode == ThemeMode.dark ? ThemeMode.light : ThemeMode.dark;
    _updateMode(target);
  }

  void setMode(ThemeMode mode) => _updateMode(mode);
  void toDark() => _updateMode(ThemeMode.dark);
  void toLight() => _updateMode(ThemeMode.light);

  @override
  Widget build(BuildContext context) => widget.builder(
        context,
        _mode,
        _instance.lightTheme,
        _instance.darkTheme,
      );
}

extension MyThemeContextExtension on BuildContext {
  _MyThemeTheme get myColors => _MyThemeTheme.of(this);
  bool get isDark => Theme.of(this).brightness == Brightness.dark;
  Color get scaffoldBackgroundColor => Theme.of(this).scaffoldBackgroundColor;
  Color get primary => Theme.of(this).primaryColor;
  Color get primaryScheme => Theme.of(this).colorScheme.primary;
  void toggleTheme() => MyThemeMaterial.of(this).toggle();
  void setThemeMode(ThemeMode mode) => MyThemeMaterial.of(this).setMode(mode);
  void toDark() => MyThemeMaterial.of(this).toDark();
  void toLight() => MyThemeMaterial.of(this).toLight();
}
